### ISSUE TITLE
Energy tracking doesn't work when only 1/2 completions are made

### ISSUE THREAD

**Issue by RyanWilkie** [Supamiu/Lostark-helper#11]
I have a character with this completion data
```
Shadiblade:Guardian:0: {amount: 1, updated: 1651732381099}
```
Rest bonus should be 30 as I only used 1 attempt on Thursday. But the app shows 20.

**Comment by Supamiu** [comment]
Hi, the issue with this is when someone opens the app but doesn't complete a task, let me explain:

 - You open the app, do everything on one character but only one guardian on character C
 - The next day, you're opening the app again, and this time, you'll skip everything on C, meaning that you should now have 30 rest bonus for guardian.
 - The day after, you finaly decide to do your guardians on C, ending up at 10 energy because you consuer 20 for the first guardian of the day.
 - Finally, the day after all this, you're skipping guardians on C again, expecting to have 30 energy after the reset.

With this process, you're expecting to have 30 energy at the end of it.

BUT as you can see in your entry (which is outdated, fwiw, completion references tasks by firestore key instead of name), it saves the time at which it was updated.

How rest bonus (energy service) works is that it compares this against last reset, and computes energy based on that. This means that you'll have the 30 energy after step 2, but since you're doing the task twice on step 3, the next update of the rest bonus will compare the fact that you didn't do the task on last rest, making it 20 rest bonus instead of the expected 30.

This is a larger scale issue because we could add rest bonus instead of setting it, but then if you open the app without doing anything two days in a row, it'll add 20 and then 40 rest bonus, ending at 60 instead of the expected 40.

Anyways, I hope this is clear enough to explain that basically, I'm not sure how to properly handle this in order to have it work as expected 😄
